### ISSUE TITLE
Doesn't appear to be working in latest release 1.4.14

### ISSUE THREAD

**Issue by jokehessle** [NemoAndrea/obsidian-daily-named-folder#2]
Hi is this still supported?

**Comment by NemoAndrea** [comment]
It still seems to be working for me on `V1.4.14`. What are the things that are not working anymore for you? If something broke I will try to fix it.

**Comment by NemoAndrea** [comment]
You were right in that the ribbon icon was broken. I never use the button, so I didn't notice; thanks for letting me know!

That should be fixed in the latest version. (it should now do the exact same thing as the command `Daily Named Folder: Open today's daily folder note`.

The other issues sound like there is something else wrong. I had something similar on a system where I did not have sufficient permissions to write in the folder. But if not you could start by just using the root folder as the base folder for the daily notes and see if that works. If not, I can try to check if you provide a bit more details (I suggest making it a new issue).

Let me know if the ribbon thing now does something after you have updated.

**Comment by HWiwoiiii** [comment]
When I try to create a new daily folder using command not ribbon icon, this error message appears - 
"Oops, something went wrong trying to make a daily-named-folder!"
I think the bug still exists

**Comment by bvn13** [comment]
Using button in left command panel I see `Oops, something went wrong trying to make daily-named-folder`. Trying to make folder using command in command palette leads to the same error message. 

plugin version v.0.1.5

obsidian version 1.9.10

internal daily-note-plugin is disabled (already tested with enabled one - the same message)

according to this block of code

```
					} else { // if template file has been moved/renamed/deleted
						new Notice('Oops, something went wrong trying to make a daily-named-folder!');
						throw "Something went wrong trying to get the template file for daily-named-folder. " +
							"Attempted to open template at " + this.settings.template;
					}
```
in [main.ts](https://github.com/NemoAndrea/obsidian-daily-named-folder/blob/37afad11c3fb7630c505534c93580f6ca596e287/main.ts#L74C18-L74C65)
I solved this issue by setting template file in plugin settings.

**Comment by NemoAndrea** [comment]
Hello @HWiwoiiii and @bvn13, I see now thanks to @bvn13 that the issue is that the plugin will not work if no template is defined, and that in that case that error will pop up. It is not a use case I had considered and I will think a bit about how to handle (maybe @bvn13 solution is fine, but I would hate for people to miss that they can easily define a template).

But as it stands, the error message is just confusing.

**Comment by NemoAndrea** [comment]
This should now be fixed. Please re-open the issue @bvn13 @HWiwoiiii if you still experience problems on `0.1.6`

**Comment by bvn13** [comment]
I think there should be an option not to use templates.

**Comment by NemoAndrea** [comment]
> I think there should be an option not to use templates.

I think that option should be present in `0.1.6`. Let me know if that isn't working.
